// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBalk.Bo
{
    public partial class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? Assignee { get; set; }
        public DateTime? DueDate { get; set; }

        public virtual User AssigneeNavigation { get; set; }
    }
}