// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBalk.Test.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataBalk.Test.Models
{
    public partial interface IDataBalkDBContextProcedures
    {
        Task<int> pr_CreateTaskAsync(string Title, string Description, int? Assignee, DateTime? DueDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> pr_DeleteTaskAsync(int? TaskID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> pr_DeleteUserAsync(int? UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetActiveTaskResult>> pr_GetActiveTaskAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetAllTasksResult>> pr_GetAllTasksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetAllUsersResult>> pr_GetAllUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetExpiredTaskResult>> pr_GetExpiredTaskAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetTaskResult>> pr_GetTaskAsync(int? TaskID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetTaskByDateResult>> pr_GetTaskByDateAsync(DateTime? Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<pr_GetUserResult>> pr_GetUserAsync(int? UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> pr_RegisterUserAsync(string Username, string Email, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> pr_UpdateTaskAsync(string Title, string Description, int? Assignee, DateTime? DueDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> pr_UpdateUserAsync(string Username, string Email, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
