// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBalk.Test.Models
{
    public partial class pr_GetAllTasksResult
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? Assignee { get; set; }
        public DateTime? DueDate { get; set; }
    }
}
